name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: ${{matrix.vector.image}}
    runs-on: ubuntu-latest
    container: ghcr.io/burlizzi/anyka_build:zlib
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd platform && make
          
    
